# Generated by Django 4.0.5 on 2022-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
